CREATE TABLE cash_flow_statements (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    symbol VARCHAR(10) NOT NULL,
    reported_currency VARCHAR(10) NOT NULL,
    cik VARCHAR(20),
    filling_date DATE,
    accepted_date DATETIME,
    calendar_year YEAR,
    period VARCHAR(5),
    net_income BIGINT,
    depreciation_and_amortization BIGINT,
    deferred_income_tax BIGINT,
    stock_based_compensation BIGINT,
    change_in_working_capital BIGINT,
    accounts_receivables BIGINT,
    inventory BIGINT,
    accounts_payables BIGINT,
    other_working_capital BIGINT,
    other_non_cash_items BIGINT,
    net_cash_provided_by_operating_activities BIGINT,
    investments_in_property_plant_and_equipment BIGINT,
    acquisitions_net BIGINT,
    purchases_of_investments BIGINT,
    sales_maturities_of_investments BIGINT,
    other_investing_activities BIGINT,
    net_cash_used_for_investing_activities BIGINT,
    debt_repayment BIGINT,
    common_stock_issued BIGINT,
    common_stock_repurchased BIGINT,
    dividends_paid BIGINT,
    other_financing_activities BIGINT,
    net_cash_used_provided_by_financing_activities BIGINT,
    effect_of_forex_changes_on_cash BIGINT,
    net_change_in_cash BIGINT,
    cash_at_end_of_period BIGINT,
    cash_at_beginning_of_period BIGINT,
    operating_cash_flow BIGINT,
    capital_expenditure BIGINT,
    free_cash_flow BIGINT,
    link VARCHAR(255),
    final_link VARCHAR(255),
    UNIQUE KEY uq_symbol_date (symbol, date)
);
